### PR TITLE
Added hyperlinkMethod prop

### PR DESCRIPTION
**Pull request by tnormington**
`hyperlinkMethod` prop allows you to generate an `xlink:href` attribute for each sector of the piechart. Currently it passes a data object with a title property, more properties could be added as needed.

The new code creates some uncovered lines in the test results, I'm not very familiar with writing tests otherwise I would cover this.

### CODE REVIEW

**Review by cedricdelpoux — CHANGES_REQUESTED** [review]
Hello @tnormington `xlink:href` seems deprecated: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href.

I would prefer you use the data array to add an `href` attribute:
`{value: number (required), color: string, title: string, expanded: bool, href: string`

Thank you for your work

**Comment by tnormington** [comment]
Good call on the xlink:href deprecation. And using an href attribute is much easier to understand. Let me know if this latest commit works.

**Review by cedricdelpoux — APPROVED** [review]

**Comment by cedricdelpoux** [comment]
It's much better, thank you @tnormington

**Comment by cedricdelpoux** [comment]
I published `v2.2.0`

**Pull request merged**
