### PR TITLE
Feature/manual expand

### PR DESCRIPTION
**Pull request by tnormington**
I added a new prop for `expandedIndex` so you can control it manually outside the component. Had to upgrade React for `getDerivedStateFromProps`, and there is 1 peer dependency warning that I couldn't resolve.

### CODE REVIEW

**Comment by cedricdelpoux** [comment]
Thank you for your help. But your PR made the build fail. There is an incompatibility with enzyme and the new React. That why I used React 15. But it will be great if you succeed to run test successfully with react 16

**Comment by tnormington** [comment]
Whoops! my bad. I'll look into using `componentDidReceiveProps` instead of `getDerivedStateFromProps` & re-submit the PR if I figure anything out.

**Comment by cedricdelpoux** [comment]
Take a look to the logs https://travis-ci.org/xuopled/react-svg-piechart/builds/371296673

**Comment by tnormington** [comment]
Are you open to upgrading to React v16 if I can get enzyme working? It looks like I may just need an adapter plugin: http://airbnb.io/enzyme/docs/installation/react-16.html

**Comment by cedricdelpoux** [comment]
Of course I am! Be my guest :)

**Comment by tnormington** [comment]
Okay I think I got it working & tests passing with React 16. I had to add an enzyme adapter, and a requestAnimationFrame shim following this comment: https://github.com/facebook/jest/issues/4545#issuecomment-332762365

I also had to exclude the shim file from the tests for full coverage.

EDIT: I will rebase this and push today to fix the merge conflict

**Comment by cedricdelpoux** [comment]
Thank you for your work. I  fixed the conflict and rebased your commits

**Comment by cedricdelpoux** [comment]
@tnormington Just releaded v2.1.0

Thank you for your help 😄

**Comment by tnormington** [comment]
Nice! Glad to help, thank for doing the rebase I was struggling 😛

**Pull request merged**
